package tomn114.com.game;

import android.app.Activity;
import android.widget.TextView;

public class BoardMaker {

    public static boolean[][][] allBoards;
    private int barrierCounter, counter = 0, runCounter = 0;
    private int barrierNum = 15;
    private int difficulty = 2;
    private int minMoves;
    private int temp;
    private int boardLength = 5;
    private int boardWidth = 5;
    private int startX, startY;
    private int endX, endY;
    private int totalMinMoves;
    private int currX, currY;


    public BoardMaker(){
        allBoards = new boolean[GamePanel.NUM_OF_LEVELS][boardLength][boardWidth];

        for(int i = 0;i<GamePanel.NUM_OF_LEVELS;i++){
            makeIt();
        }
    }

    //Creates the board by calling makeBoard
    public void makeIt(){
        runCounter++;
        startX = 0;
        startY = 0;
        endX = 4;
        endY = 4;
        barrierCounter = barrierNum;
        //generates random barriers
        for(int i=0; i < boardLength; i++){
            for(int j=0; j < boardWidth; j++){
                temp = (int)(Math.random()*3);
                if(temp==0 && barrierCounter!=0){
                    allBoards[counter][i][j] = false;
                    barrierCounter--;
                }
                else allBoards[counter][i][j] = true;
            }
        }
        //Lowers the difficulty if a level cannot be generated by 8000 levels
        //Prevents StackOverflow
        if(runCounter == 8000){
            runCounter = 0;
            difficulty--;
        }

        allBoards[counter][startX][startY] = true;
        allBoards[counter][endX][endY] = true;
        minMoves = BoardUtilities.checkBoard(allBoards[counter],startX, startY, endX, endY, boardLength, boardWidth);

        //If the board is not possible to complete it will re-call the method
        if(minMoves==boardLength*boardWidth || minMoves<=difficulty)makeIt();
        else{
            barrierNum = 15;
            difficulty++;
            counter++;
            totalMinMoves+=minMoves;
        }
    }
}
